vim.g.mapleader = ' '

local zk = require("zk")
local commands = require("zk.commands")
commands.add("ZkOrphans", function(options)
  options = vim.tbl_extend("force", { orphan = true }, options or {})
  zk.edit(options, { title = "Zk Orphans" })
end)
local opts = { noremap = true, silent = false }
local sil = { noremap = true, silent = true }

--vim.api.nvim_set_keymap('n', '<leader>lt', ':NoNeckPain<CR>|<C-w><Left>|:terminal<CR>i', { noremap = true })
--vim.api.nvim_set_keymap('n', '<leader>t', ':TodoLocList<CR>', { noremap = true })
--vim.api.nvim_set_keymap('n', '<leader><C-f>', ':%s@', { noremap = true })
vim.api.nvim_set_keymap("n", "<F5>", ":retab", opts)
vim.api.nvim_set_keymap("n", "<F6>", ":let _s=@/<Bar>:%s/\\s\\+$//e<Bar>:let @/=_s<Bar><CR>", opts)
vim.api.nvim_set_keymap("n", "<leader><BS>", "<Cmd>MkdnSTab<CR>", sil)
vim.api.nvim_set_keymap("n", "<leader><Tab>", "<Cmd>MkdnTab<CR>", sil)
vim.api.nvim_set_keymap("n", "<leader>c", "<Cmd>nohlsearch<CR>", sil)
vim.api.nvim_set_keymap("n", "<leader>t", "<Cmd>MkdnTableFormat<CR>", sil)
vim.api.nvim_set_keymap("n", "<leader>x", "<Cmd>MkdnToggleToDo<CR>", sil)
vim.api.nvim_set_keymap("n", "<leader>zb", "<Cmd>ZkBacklinks<CR>", opts)
vim.api.nvim_set_keymap("n", "<leader>zf", "<Cmd>ZkNotes { sort = { 'modified' } }<CR>", opts)
vim.api.nvim_set_keymap("n", "<leader>zl", "<Cmd>ZkLinks<CR>", opts)
vim.api.nvim_set_keymap("n", "<leader>zn", "<Cmd>ZkNew { dir = vim.fn.expand('%:p:h'), title = vim.fn.input('Title: ') }<CR>", opts)
vim.api.nvim_set_keymap("n", "<leader>zn", "<Cmd>ZkNew { title = vim.fn.input('Title: ') }<CR>", opts)
vim.api.nvim_set_keymap("n", "<leader>zo", "<Cmd>ZkOrphans<CR>", opts)
vim.api.nvim_set_keymap("n", "<leader>zs", "<Cmd>ZkNotes { sort = { 'modified' }, match = { vim.fn.input('Search: ') } }<CR>", opts)
vim.api.nvim_set_keymap("n", "<leader>zt", "<Cmd>ZkTags<CR>", opts)
vim.api.nvim_set_keymap("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>", opts)
vim.api.nvim_set_keymap("n", "gp", "[v]", opts)
vim.api.nvim_set_keymap('n', '<leader>bb', ':Buffers<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>bd', ':bd<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>bw', ':bw!<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>ff', ':Files<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>k', ':!kitty &<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>l', ':Lazy<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>n', ':NoNeckPain<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>ob', ':VimtexCompile<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>oo', ':!zetpdf %<CR>', sil)
vim.api.nvim_set_keymap('n', '<leader>vv', '<C-w>v<CR><C-w><Right>', sil)
vim.api.nvim_set_keymap('n', '<leader>zb', ':ZkBacklinks<CR>', sil)

vim.cmd([[tnoremap <Esc> <C-\><C-n>]])

vim.api.nvim_set_keymap("v", "<leader>s", ":'<,'>sort /[^<]*</<CR>", sil)
vim.api.nvim_set_keymap("v", "<leader>za", ":'<,'>lua vim.lsp.buf.range_code_action()<CR>", opts)
vim.api.nvim_set_keymap("v", "<leader>znc", ":'<,'>ZkNewFromContentSelection { dir = vim.fn.expand('%:p:h'), title = vim.fn.input('Title: ') }<CR>", opts)
vim.api.nvim_set_keymap("v", "<leader>znt", ":'<,'>ZkNewFromTitleSelection { dir = vim.fn.expand('%:p:h') }<CR>", opts)
vim.api.nvim_set_keymap("v", "<leader>zs", ":'<,'>ZkMatch<CR>", opts)
vim.api.nvim_set_keymap('v', '<leader>zi', ':ZkInsertLinkAtSelection<CR>', sil)
