#!/usr/bin/env bash
# requires brightnessctl

#limit=60
#if [[ "$1" == "see" ]]; then
#    brightnessctl
#elif [[ "$1" == "help" ]]; then
#    printf "Sample use:\n"
#    printf "screen 80 \t - \t sets brightness to 80%%\n"
#    printf "screen see \t - \t view current brightness\n"
#    printf "screen help \t - \t view this help\n"
#    printf "Edit the \$limit value if you want to go lower than $limit%%. For some reason.\n"
#elif [[ $1 -lt $limit ]]; then
#    printf 'no'
#else
#    brightnessctl set $1%
#fi

limit=60
adjustBrightness() {
    if [[ "$1" == "see" ]]; then
        brightnessctl
    elif [[ $1 -lt $limit ]]; then
        printf 'no'
    else
        brightnessctl set $1%
    fi
}

printHelp() {
    if [[ "$1" == "help" || "$1" == "" ]]; then
        printf "This script sets the screen brightness based on a given percentage.\nBeats typing \"brightnessctl 80%%\" and then realizing you forgot the percent sign!\n"
        printf "Sample use:\n"
        printf "brightness 80 \t - \t sets brightness to 80%%\n"
        printf "brightness see \t - \t view current brightness\n"
        printf "brightness help \t - \t view this help\n"
        printf "Edit the \$limit value in the script if you want to go lower than $limit%%. For some reason.\n"
    else
        adjustBrightness "$1"
    fi
}

#brightnessctl set 80
#sleep 1
#brightnessctl set 100%
printHelp "$1"
