#!/usr/bin/env bash

langvar=$(trans -identify "$1" | head -n 1 | sed -r 's~\x01?(\x1B\(B)?\x1B\[([0-9;]*)?[JKmsu]\x02?~~g')

if [ "$langvar" == "Deutsch" ]; then
    trans de:en "$1"
elif [ "$langvar" == "English" ]; then
    trans en:de "$1"
else
    trans :en "$1"
fi
