# -*- indent-tabs-mode: nil; -*-
directory: ~/music
library: ~/.config/beets/musiclibrary.db
import:
    write: yes
    move: yes
    copy: no
    incremental: no
    autotag: yes
plugins: chroma mbsync smartplaylist replaygain fish badfiles inline lyrics duplicates convert edit alternatives
paths:
    default: external/$albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
    singleton: external/$albumartist/$album%aunique{}/$track $title
    comp: external/Various Artists/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
item_fields:
    multidisc: 1 if disctotal > 1 else 0
convert:
    dest: ~/music-android
chroma:
    auto: yes
lyrics:
    auto: yes
replaygain:
    auto: no
    backend: ffmpeg
smartplaylist:
    playlist_dir: ~/music/playlists
    forward_slash: no
    relative_to: ~/music
    playlists:
        - name: everything.m3u
          query: ''

        - name: deutschemusik.m3u
          query: ['artist:"All diese Gewalt"',
                  'artist:"And One"',
                  'artist:"AnnenMayKantereit"',
                  'artist:"Badchieff"',
                  'artist:"Bausa"',
                  'artist:"Bela B"',
                  'artist:"Blind Guardian"',
                  'artist:"Blutengel"',
                  'artist:"Bodo Wartke"',
                  'artist:"Böhse Onkelz"',
                  'artist:"Broilers"',
                  'artist::^CRO$',
                  'artist:"Cephalgy"',
                  'artist::^Cro$',
                  'artist:"Covenant"',
                  'artist:"Das Ich"',
                  'artist:"Das Lumpenpack"',
                  '"artist:David Bowie" "helden"',
                  'artist:"Diary of Dreams"',
                  'artist:"Die Kreatur"',
                  'artist:"Die Krupps"',
                  'artist:"Die Lochis"',
                  'artist:"Die Swing Jugend"',
                  'artist:"Die Toten Hosen"',
                  'artist:"Die Ärzte"',
                  'artist:"Die Wilde Jagd"',
                  'artist:"Egotronic"',
                  'artist:"Eisbrecher"',
                  'artist:"Erdling"',
                  'artist:"Falco"',
                  'artist:"Farin Urlaub"',
                  'artist:"Farin Urlaub Racing Team"',
                  'artist:"Faun"',
                  'artist:"Feindflug"',
                  'artist:"Ferris MC"',
                  'artist:"Feuerschwanz"',
                  'artist:"Frank Wildhorn"',
                  'artist:"Franz Schubert"',
                  'artist:"Fritz Kreisler"',
                  'artist:"Funker Vogt"',
                  'artist:"Hanzel und Gretyl"',
                  'artist:"Heldmaschine"',
                  'artist:"Henning May"',
                  'artist:"Heppner"',
                  'artist:"Hämatom"',
                  'artist:"In Strict Confidence"',
                  'artist:"Jacques Higelin"',
                  'artist:"Joachim Witt"',
                  'artist:"Josè Alvarez Brill & Peter Heppner"',
                  'artist:"Kraftklub"',
                  'artist:"Kraftwerk"',
                  'artist:"Kärbholz"',
                  'artist:"KMFDM"',
                  'artist::^LOTTE$',
                  'artist:"Laibach"',
                  'artist::^Lotte$',
                  'artist::^Love A$',
                  'artist:"Marlene Dietrich"',
                  'artist:^Marv$',
                  'artist:"Matthias Reim"',
                  'artist:"Megaherz"',
                  'artist:"Mono Inc"',
                  'artist:"Nachtmahr"',
                  'artist:"Nena"',
                  'artist:"Nick & Simon"',
                  'artist:"OOMPH!"',
                  'artist:"Oomph!"',
                  'artist:"Orange Sector"',
                  'artist:"Ost+Front"',
                  'artist:"Peter Heppner"',
                  'artist:"Peter Schilling"',
                  'artist:"Project Pitchfork"',
                  '"artist:Phil Collins" "fremde"',
                  'artist:"Philipp Dittberner"',
                  'artist:"Philipp Dittberner & Marv"',
                  'artist:"Powerwolf"',
                  'artist:"Rammstein"',
                  'artist:"Raphaël"',
                  'artist:"Rave.dj"',
                  'artist:"Robert Schumann"',
                  'artist:"Rotersand"',
                  'artist:"Rummelsnuff"',
                  'artist:"SIRA"',
                  'artist:"Samsas Traum"',
                  'artist:"Schattenmann"',
                  'artist:"Schwarzer Engel"',
                  'artist:"Sodom"',
                  'artist:"Solomun"',
                  'artist:"Spider Murphy Gang"',
                  'artist:"Stoneman"',
                  'artist:"Tanzwut"',
                  'artist:"Terminal Choice"',
                  'artist:"Theater an der Wien"',
                  'artist:"Till Lindemann"',
                  'artist:"Tim Bendzko"',
                  'artist:"Udo Jürgens"',
                  'artist:"Unheilig"',
                  'artist:"Valborg"',
                  'artist:"Wir sind Helden"',
                  'artist:"Wolfsheim"',
                  'artist:"[die!]"',
                  'artist:"voXXclub"',
                  'artist:"witt"',
                  'artist:"Willkuer"']

        - name: belafarinrod.m3u
          query: ['artist:"Bela B"',
                  'artist:"Die Ärzte"',
                  'artist:"Farin Urlaub"',
                  'artist:"Farin Urlaub Racing Team"']

        - name: aufenglisch.m3u # extra music I want on my phone
          query: ['artist:"A Perfect Circle"',
                  'artist:"Ace of Base"',
                  'artist:"Angelspit"',
                  'artist:"Assemblage 23"',
                  'artist:"Beck"',
                  'artist:"Chumbawamba"',
                  'artist:"David Arkenstone"',
                  'artist:"Depeche Mode"',
                  'artist:"FGFC820"',
                  'artist:"Gary Numan"',
                  'artist:"Jack Stauber"',
                  'artist:"KLF"',
                  'artist:"MDFMK"',
                  'artist:"Ministry"',
                  'artist:"Mortiis"', # die krupps remix
                  'artist:"Nine Inch Nails"',
                  'artist:"Patient Zero"',
                  'artist:"Pseudo Echo"',
                  'artist:"Rob Zombie"',
                  'artist:"Robbie Williams"',
                  'artist:"Siouxsie & The Banshees"',
                  'artist:"Siouxsie and the Banshees"',
                  'artist:"Sisters of Mercy"',
                  'artist:"The Avalanches"',
                  'artist:"The Hunger"',
                  'artist:"The Timelords"',
                  'artist:"Utah Saints"',
                  'artist:"Various Artists"',
                  'artist:"White Zombie"',
                  'artist:"deadmau5"']

alternatives:
    droid:
      directory: ~/music-android
      paths:
        default: external/$albumartist/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
        singleton: external/$albumartist/$album%aunique{}/$track $title
        comp: external/Various Artists/$album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
      formats: opus mp3
      #query: "onplayer:true"
      query:
        "'All diese Gewalt',
        'And One',
        'AnnenMayKantereit',
        'Badchieff',
        'Bausa',
        'Bela B',
        'Blind Guardian',
        'Blutengel',
        'Bodo Wartke',
        'Böhse Onkelz',
        'Broilers',
        'artist::^CRO$',
        'Cephalgy',
        'artist::^Cro$',
        'Covenant',
        'Das Ich',
        'Das Lumpenpack',
        'David Bowie helden',
        'Diary of Dreams',
        'Die Kreatur',
        'Die Krupps',
        'Die Lochis',
        'Die Swing Jugend',
        'Die Toten Hosen',
        'Die Ärzte',
        'Die Wilde Jagd',
        'Egotronic',
        'Eisbrecher',
        'Erdling',
        'Falco',
        'Farin Urlaub',
        'Farin Urlaub Racing Team',
        'Faun',
        'Feindflug',
        'Ferris MC',
        'Feuerschwanz',
        'Frank Wildhorn',
        'Franz Schubert',
        'Fritz Kreisler',
        'Funker Vogt',
        'Hanzel und Gretyl',
        'Heldmaschine',
        'Henning May',
        'Heppner',
        'Hämatom',
        'In Strict Confidence',
        'Jacques Higelin',
        'Joachim Witt',
        'Josè Alvarez Brill & Peter Heppner',
        'Kraftklub',
        'Kraftwerk',
        'Kärbholz',
        'KMFDM',
        'artist::^LOTTE$',
        'Laibach',
        'artist::^Lotte$',
        'artist::^Love A$',
        'Marlene Dietrich',
        'artist:^Marv$',
        'Matthias Reim',
        'Megaherz',
        'Mono Inc',
        'Nachtmahr',
        'Nena',
        'Nick & Simon',
        'OOMPH!',
        'Oomph!',
        'Orange Sector',
        'Ost+Front',
        'Peter Heppner',
        'Peter Schilling',
        'Project Pitchfork',
        'Phil Collins fremde',
        'Philipp Dittberner',
        'Philipp Dittberner & Marv',
        'Powerwolf',
        'Rammstein',
        'Raphaël',
        'Rave.dj',
        'Robert Schumann',
        'Rotersand',
        'Rummelsnuff',
        'SIRA',
        'Samsas Traum',
        'Schattenmann',
        'Schwarzer Engel',
        'Sodom',
        'Solomun',
        'Spider Murphy Gang',
        'Stoneman',
        'Tanzwut',
        'Terminal Choice',
        'Theater an der Wien',
        'Till Lindemann',
        'Tim Bendzko',
        'Udo Jürgens',
        'Unheilig',
        'Valborg',
        'Wir sind Helden',
        'Wolfsheim',
        '[die!]',
        'voXXclub',
        'witt',
        'Willkuer',
        'Bela B',
        'Die Ärzte',
        'Farin Urlaub',
        'Farin Urlaub Racing Team',
        'A Perfect Circle',
        'Ace of Base',
        'Angelspit',
        'Assemblage 23',
        'Beck',
        'Chumbawamba',
        'David Arkenstone',
        'Depeche Mode',
        'FGFC820',
        'Gary Numan',
        'I DONT KNOW HOW BUT THEY FOUND ME',
        'Jack Stauber',
        'KLF',
        'MDFMK',
        'Ministry',
        'Mortiis',
        'Nine Inch Nails',
        'Patient Zero',
        'Pseudo Echo',
        'Rob Zombie',
        'Robbie Williams',
        'Siouxsie & The Banshees',
        'Siouxsie and the Banshees',
        'Sisters of Mercy',
        'The Avalanches',
        'The Hunger',
        'The Timelords',
        'Utah Saints',
        'Various Artists',
        'White Zombie',
        'deadmau5'"
      removable: false
