#!/bin/bash
choice=0
confirm=0

if [[ $1 = a* ]]
then
	echo "You can't backup to your home partitions!"
else
	if mountpoint -q /run/media/jet/pony 
	then
	   echo "Drive mounted."
		#echo "1: full backup, excludes home and etc"
		echo -n "2: only changed files, excludes: "
		echo $(<$XDG_DOCUMENTS_DIR/rsync-list.txt)
		echo $(<rsync-list.txt)
		#echo "3: just music folder"
		read choice

		echo files or bars? [f/b]
		read confirm
		#if [[ $choice = "1" && $confirm = "f" ]]
		#then
		#	sudo rsync -aAXHv --delete --exclude={"swapfile","/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found",".cache/*","/etc/*","/home/*","/usr/*"} / /run/media/jet/pony/sharky/
		#	udisksctl unmount --block-device /dev/sd$1
		#	echo "USB unmounted."
		if [[ $choice = "2" && $confirm = "f" ]]
		then
			sudo rsync -avu --delete --exclude-from='rsync-list.txt' /home/ /run/media/jet/pony/sharky/home/
			sync &&
			udisksctl unmount --block-device /dev/sd$1
			echo "USB unmounted."
		elif [[ $choice = "2" && $confirm = "b" ]]
		then
			sudo rsync -au --info=progress2 --delete --exclude-from=$XDG_DOCUMENTS_DIR/rsync-list.txt /home/ /run/media/jet/pony/sharky/home/
			udisksctl unmount --block-device /dev/sd$1
			echo "USB unmounted."
		else
			echo "Exiting."
			#sudo rsync -aAXHv --delete --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found",".cache/*","/etc/*","/home/*","/usr/*"} / /run/media/jet/pony/sharky/
		fi
	else
		echo "dev/sd$1 is not mounted!"
	fi
fi
