#!/bin/env bash
now=$(date +"%Y%m%d-%H%M%S")
echo "---" | tee -a $ZETTELKASTEN/$now.md
echo "tags:" | tee -a $ZETTELKASTEN/$now.md
echo "- $2" | tee -a $ZETTELKASTEN/$now.md
echo "---" | tee -a $ZETTELKASTEN/$now.md
echo "" | tee -a $ZETTELKASTEN/$now.md
echo "$%! TEX root = $ZETTELKASTEN$now.md$" | tee -a $ZETTELKASTEN/$now.md
echo "" | tee -a $ZETTELKASTEN/$now.md
echo "# $1" | tee -a $ZETTELKASTEN/$now.md
cd $ZETTELKASTEN
nvim +/# $now.md
