#!/bin/env bash
# original
#pacman -Qqe | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(sudo pacman -Rns {})'
pacman -Qqe | fzf --preview 'pacman -Qi {}' --layout=reverse --bind 'enter:execute(sudo pacman -Rns {})'

#pacman -Qqe | fzf --multi --preview 'pacman -Qi {1}' --layout=reverse --bind 'enter:execute(sudo pacman -Rns {1}),space:execute(pacman -Qil {} | less)'

#pacman -Qqe | fzf --multi --preview 'pacman -Qi {1}' --layout=reverse --bind 'space:execute(pacman -Qil {} | less),enter:execute(sudo pacman -Rns {})'


# from wiki
#pacman -Qqe | fzf --multi --preview 'pacman -Qi {1}' --layout=reverse | xargs -ro sudo pacman -Rns
