#!/usr/bin/env bash

HOSTNAME=$(cat /etc/hostname)
if [[ $1 = sda* && $HOSTNAME = "sharky" ]]
then
	echo "You can't eject your home partitions!"
else
	sync
	udisksctl unmount --block-device /dev/"$1"
fi
