board_manager:
    additional_urls:
        - http://arduino.esp8266.com/stable/package_esp8266com_index.json
        - https://dl.espressif.com/dl/package_esp32_index.json
build_cache:
    compilations_before_purge: 10
    ttl: 720h0m0s
daemon:
    port: "50051"
directories:
    builtin:
        libraries: /home/jet/.local/share/arduino15/libraries
    data: /home/jet/.local/share/arduino15
    downloads: /home/jet/.local/share/arduino15/staging
    user: /home/jet/docs/notes/projects/arduino
library:
    enable_unsafe_install: false
locale: en
logging:
    file: ""
    format: text
    level: info
metrics:
    addr: :9090
    enabled: false
output:
    no_color: false
sketch:
    always_export_binaries: false
updater:
    enable_notification: true
