#!/usr/bin/env bash

cd $ZETTELKASTEN
mkdir $ZETTELKASTEN/.mytrash

find . -maxdepth 1 -name "*.aux" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fls" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fdb_latexmk" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.log" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.gz" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.out" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.in" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.lua" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.xdv" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.run.xml" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.blg" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.bbl" -exec mv {} $ZETTELKASTEN/.mytrash/ \;

cd $ZETTELKASTEN/fleeting
find . -maxdepth 1 -name "*.aux" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fls" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fdb_latexmk" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.log" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.gz" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.out" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.in" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.lua" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.xdv" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.run.xml" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.blg" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.bbl" -exec mv {} $ZETTELKASTEN/.mytrash/ \;

cd

cd $XDG_DOCUMENTS_DIR/notes/notes-texstories
find . -name "*.aux" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.fls" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.fdb_latexmk" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.log" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.gz" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.markdown.out" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.markdown.in" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.markdown.lua" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.xdv" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.run.xml" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.blg" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.bbl" -exec mv {} $ZETTELKASTEN/.mytrash/ \;

cd

cd $XDG_DOCUMENTS_DIR/notes/school/COM1000
find . -name "*.aux" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.fls" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.fdb_latexmk" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.log" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.gz" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.markdown.out" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.markdown.in" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.markdown.lua" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.xdv" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.run.xml" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.blg" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -name "*.bbl" -exec mv {} $ZETTELKASTEN/.mytrash/ \;

rm -r $ZETTELKASTEN/.mytrash
