#!/usr/bin/env bash

# requires pacman-contrib
# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Not_in_a_specified_group,_repository_or_meta_package

sudo pacman -Qtdq | sudo pacman -Rns -
sudo pacman -Qqd | sudo pacman -Rsu -
sudo rm -rfv $XDG_CACHE_HOME/paru/clone
mkdir $XDG_CACHE_HOME/paru/clone
sudo paccache -rk1
sudo paccache -ruk0
pacman -Qqe > $XDG_DOCUMENTS_DIR/paclist/pkglist-$(cat /etc/hostname).txt
comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort) > $XDG_DOCUMENTS_DIR/paclist/optdeplist-$(cat /etc/hostname).txt
pacman -Qqem > $XDG_DOCUMENTS_DIR/paclist/foreignpkglist-$(cat /etc/hostname).txt
