#!/usr/bin/env bash
rm -i $(find $ZETTELKASTEN -empty -print)
cd $ZETTELKASTEN
mkdir $ZETTELKASTEN/.mytrash

find . -maxdepth 1 -name "*.aux" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fls" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fdb_latexmk" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.log" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.gz" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.out" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.in" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.lua" -exec mv {} $ZETTELKASTEN/.mytrash/ \;

cd $ZETTELKASTEN/fleeting
find . -maxdepth 1 -name "*.aux" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fls" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fdb_latexmk" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.log" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.gz" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.out" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.in" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.markdown.lua" -exec mv {} $ZETTELKASTEN/.mytrash/ \;

rm -r $ZETTELKASTEN/.mytrash
