#!/bin/bash

#rsync -a --delete .config/whoozle.github.io/ $PROJECTS/git/newdots/.config/whoozle.github.io/
rsync -a --delete --exclude={"/plugged/*","/autoload/*"} .config/nvim/ $PROJECTS/git/newdots/.config/nvim/
rsync -a --delete --exclude={"/plugged/**"} .config/nvim-old/ $PROJECTS/git/newdots/.config/nvim-old/
rsync -a --delete .config/X11/ $PROJECTS/git/newdots/.config/X11/
#rsync -a --delete .config/ctpv/ $PROJECTS/git/newdots/.config/ctpv/
rsync -a --delete .config/pistol/ $PROJECTS/git/newdots/.config/pistol/
rsync -a --delete .config/czkawka/ $PROJECTS/git/newdots/.config/czkawka/
rsync -a --delete .config/dunst/ $PROJECTS/git/newdots/.config/dunst/
rsync -a --delete .config/fish/ $PROJECTS/git/newdots/.config/fish/
rsync -a --delete .config/kitty/ $PROJECTS/git/newdots/.config/kitty/
rsync -a --delete .config/lf/ $PROJECTS/git/newdots/.config/lf/
rsync -a --delete .config/mpd/ $PROJECTS/git/newdots/.config/mpd/
#rsync -a --delete --exclude={"lrc.lua","lrc.conf"} .config/mpv/ $PROJECTS/git/newdots/.config/mpv/
rsync -a --delete .config/mpv/ $PROJECTS/git/newdots/.config/mpv/
#rsync -a --delete .config/ncmpcpp/ $PROJECTS/git/newdots/.config/ncmpcpp/
rsync -a --delete .config/neofetch/ $PROJECTS/git/newdots/.config/neofetch/
rsync -a --delete .config/newsboat/ $PROJECTS/git/newdots/.config/newsboat/
rsync -a --delete .config/nvim/ $PROJECTS/git/newdots/.config/nvim/
rsync -a --delete .config/paru/ $PROJECTS/git/newdots/.config/paru/
rsync -a --delete .config/swappy/ $PROJECTS/git/newdots/.config/swappy/
rsync -a --delete .config/sway/ $PROJECTS/git/newdots/.config/sway/
rsync -a --delete .config/waybar/ $PROJECTS/git/newdots/.config/waybar/
rsync -a --delete .config/zathura/ $PROJECTS/git/newdots/.config/zathura/
rsync -a --delete /etc/pacman.conf $PROJECTS/git/newdots/etc/pacman.conf
rsync -a --delete /etc/xdg/reflector/ $PROJECTS/git/newdots/etc/xdg/reflector
rsync -a --delete docs/scripts/ $PROJECTS/git/newdots/docs/scripts/
rsync -a --delete $XDG_PICTURES_DIR/wallpapers/fox.jpg $PROJECTS/git/newdots/pics/wallpapers/fox.jpg
cd $PROJECTS/git/newdots
