#!/usr/bin/env fish

set -gx SDL_VIDEODRIVER wayland
set -gx _JAVA_AWT_WM_NONREPARENTING 1
#set -gx QT_QPA_PLATFORM wayland
set -gx XDG_CURRENT_DESKTOP sway
set -gx XDG_SESSION_DESKTOP sway
#set myname (cat /etc/hostname)
#if [ $myname = "sharky" ]
#    systemctl --user start opentabletdriver
#end
dbus-run-session sway -c $XDG_CONFIG_HOME/sway/config-$(cat /etc/hostname)
