#!/usr/bin/env bash
cd $HOME
cd $ZETTELKASTEN/fleeting/
now=$(date +"%Y%m%d-%H%M%S")
#set now $(date +"%Y%m%d-%H%M%S")
echo "%! TEX root = $ZETTELKASTEN$now.tex" | tee -a $now.tex
echo "\documentclass[$2]{scrartcl}" | tee -a $now.tex
echo "\title{$1}" | tee -a $now.tex
echo "\author{JetpackJackson}" | tee -a $now.tex
echo "%\usepackage{babel}" | tee -a $now.tex
echo "%\usepackage{markdown} requires texlive-plaingeneric" | tee -a $now.tex
echo "\begin{document}" | tee -a $now.tex
echo "\maketitle" | tee -a $now.tex
echo "" | tee -a $now.tex
echo "#" | tee -a $now.tex
echo "" | tee -a $now.tex
echo "\end{document}" | tee -a $now.tex
nvim +/# $now.tex
