#!/bin/bash
rm -i $(find $ZETTELKASTEN -empty -print)
cd $ZETTELKASTEN
#movefiletype aux
#movefiletype fls
#movefiletype fdb_latexmk
#movefiletype gz
mkdir $ZETTELKASTEN.mytrash
#mv $ZETTELKASTEN/aux/* $ZETTELKASTEN/.mytrash
#mv $ZETTELKASTEN/fls/* $ZETTELKASTEN/.mytrash
#mv $ZETTELKASTEN/fdb_latexmk/* $ZETTELKASTEN/.mytrash
#mv $ZETTELKASTEN/gz/* $ZETTELKASTEN/.mytrash

find . -maxdepth 1 -name "*.aux" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fls" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.fdb_latexmk" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.log" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
find . -maxdepth 1 -name "*.gz" -exec mv {} $ZETTELKASTEN/.mytrash/ \;
rm -r $ZETTELKASTEN.mytrash
