#!/bin/bash
sudo pacman -Qtdq | sudo pacman -Rns -
sudo pacman -Qqd | sudo pacman -Rsu -
sudo paccache -rk1
sudo paccache -ruk0
pacman -Qqe > ~/docs/paclist/pkglist.txt
comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort) > ~/docs/paclist/optdeplist.txt
pacman -Qqem > ~/docs/paclist/foreignpkglist.txt
