#!/bin/bash
sudo pacman -Qtdq | sudo pacman -Rns -
sudo pacman -Qqd | sudo pacman -Rsu -
sudo paccache -rk1
sudo paccache -ruk0
pacman -Qqe > $XDG_DOCUMENTS_DIR/paclist/pkglist.txt
comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort) > $XDG_DOCUMENTS_DIR/paclist/optdeplist.txt
pacman -Qqem > $XDG_DOCUMENTS_DIR/paclist/foreignpkglist.txt
