#!/usr/bin/env bash

# requires pacman-contrib
# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Not_in_a_specified_group,_repository_or_meta_package
distro=$(awk '{ print $1 }' <(cat /etc/os-release | sed 's/.*=//') | head -n3 | tail -n1)
if [[ $distro = "arch" || $distro = "artix" ]]; then
    sudo pacman -Qtdq | sudo pacman -Rns -
    sudo pacman -Qqd | sudo pacman -Rsu -
    #sudo rm -rfv $XDG_CACHE_HOME/paru/clone
    rm -rv $XDG_CACHE_HOME/paru/clone
    mkdir $XDG_CACHE_HOME/paru/clone
    sudo paccache -rk1
    sudo paccache -ruk0
    pacman -Qqe > $XDG_DOCUMENTS_DIR/notes/paclist/pkglist-$(cat /etc/hostname).txt
    comm -13 <(pacman -Qqdt | sort) <(pacman -Qqdtt | sort) > $XDG_DOCUMENTS_DIR/notes/paclist/optdeplist-$(cat /etc/hostname).txt
    pacman -Qqem > $XDG_DOCUMENTS_DIR/notes/paclist/foreignpkglist-$(cat /etc/hostname).txt
fi
# texlive
# sudo tlmgr list --only-installed --data name > $XDG_DOCUMENTS_DIR/notes/paclist/installed_texlive_packages-$(cat /etc/hostname).txt
# to retrieve (untested): tlmgr install < $XDG_DOCUMENTS_DIR/scripts/installed_texlive_packages.txt
