#!/bin/env bash

if [[ $(cat /etc/hostname) == "greyfox" ]]
    sudo grub-install --target=x86_64-efi --efi-directory=/boot/EFI/GRUB/ --bootloader-id=GRUB
    grub-mkconfig -o /boot/grub/grub.cfg
elif [[ $(cat /etc/hostname) == "sharky" ]]
    sudo grub-install --target=i386-pc /dev/sda
    grub-mkconfig -o /boot/grub/grub.cfg
fi
