#!/bin/bash
#ncmpcpp --current-song %D/%f -q
a='/home/jet/Music/'
b="$(ncmpcpp --current-song %D/%f -q)"
c="${a}${b}"
#echo "${c}" > nowplaying.txt 2>&1
ffprobe "${c}" > lyrics.txt 2>&1
#exec sed -n '/lyrics-XXX/,/Duration/p' lyrics.txt | less
exec sed '/lyrics-XXX/,/Duration/!d' lyrics.txt | less

#exec sed '$d' lyrics.txt
#exec sed '/Duration:/d' lyrics.txt
#cat lyrics.txt
