#!/bin/bash
#a='/home/jet/Music/'
a=$XDG_MUSIC_DIR/
b="$(mpc current -f %file%)"
c="${a}${b}"
ffprobe "${c}" > /home/jet/.cache/mylyrics/lyrics.txt 2>&1
exec sed '/lyrics-XXX/,/Duration/!d' /home/jet/.cache/mylyrics/lyrics.txt | less
