#!/bin/bash
choice=0
echo "1: mount"
echo "2: unmount"
read choice
case "$choice" in
    1) sudo mount --bind /run/media/jet/Crucial\ X6/MUSIC/ /home/jet/music/external
       notify-send "music mounted"
    ;;
    2) sudo umount /home/jet/music/external
       notify-send "music unmounted"
    ;;
    *) echo "Try again."
    ;;
esac
