#!/bin/bash
#now=$(date +"%Y-%m-%d-%H%M")
now=$(date +"%Y%m%d-%H%M%S")
echo "$%! TEX root = $ZETTELKASTEN$now.md$" | tee -a $ZETTELKASTEN/$now.md
#echo "\documentclass{$1}" | tee -a $ZETTELKASTEN/$now.md
#echo "\begin{document}" | tee -a $ZETTELKASTEN/$now.md
#echo "\end{document}" | tee -a $ZETTELKASTEN/$now.md
echo "" | tee -a $ZETTELKASTEN/$now.md
echo "---" | tee -a $ZETTELKASTEN/$now.md
echo "tags:" | tee -a $ZETTELKASTEN/$now.md
echo "- $2" | tee -a $ZETTELKASTEN/$now.md
echo "---" | tee -a $ZETTELKASTEN/$now.md
echo "" | tee -a $ZETTELKASTEN/$now.md
echo "# $1" | tee -a $ZETTELKASTEN/$now.md
nvim +/# $ZETTELKASTEN/$now.md
