#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Here i3 is kept as default
#session=${1:-i3}
#
#case $session in
#    i3|i3wm           ) exec i3;;
#    spectrwm          ) exec spectrwm;;
#    xfce|xfce4        ) exec startxfce4;;
#    # No known session, try to run it as command
#    *                 ) exec $1;;
#esac

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#autocutsel -fork &
#autocutsel -selection PRIMARY -fork &

#greenclip daemon &
#udiskie &
#i3
#xclock -geometry 50x50-1+1 &
#kitty -geometry 80x50+494+51 &
#kitty -geometry 80x20+494-0 &
#exec kitty -geometry 80x66+0+0 -name login
#exec leftwm
exec dwm
