return {
  { "folke/trouble.nvim", enabled = false },
  { "L3MON4D3/LuaSnip", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "jose-elias-alvarez/null-ls.nvim", enabled = false },
--  { "hrsh7th/cmp-nvim-lsp", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
-- { "williamboman/mason.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "folke/neodev.nvim", enabled = false },
-- { "williamboman/mason-lspconfig.nvim", enabled = false },
  { "ms-jpq/coq_nvim", enabled = false },
--  { "hrsh7th/nvim-cmp", enabled = false },
--  { "hrsh7th/cmp-buffer", enabled = false },
--  { "neovim/nvim-lspconfig", enabled = false },
}
